# For Nodejs

FROM kerkerj:ubuntu
MAINTAINER Jerry Huang (jerry.huang@livebricks.com)
RUN sudo apt-get -qq update 
RUN apt-get update --fix-missing
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

#RUN apt-get install -y supervisor
#RUN mkdir -p /var/log/supervisor

# NVM
RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.19.0/install.sh | bash && \
  source ~/.nvm/nvm.sh && \
  nvm install 0.10 && \
  nvm alias default 0.10 && \
  echo 'export NVM_DIR="/root/.nvm"' >> ~/.zshrc && \
  echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' >> ~/.zshrc && \
  n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib} /usr/local 

# Cleanup
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN apt-get autoremove -y

#ADD ./supervisord.conf /etc/supervisor/conf.d/supervisord-nodejs.conf

# modify configs
#RUN rm /etc/nginx/sites-enabled/default
#ADD nodejs.conf /etc/nginx/sites-enabled/

# Sample server
RUN mkdir /webapp
ADD sample_server.js /webapp/sample_server.js

EXPOSE 20 80 8080

WORKDIR /webapp
CMD ["node", "/webapp/sample_server.js"]
#CMD service nginx start